// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:assets/assets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
sealed class Environment {
  static FirebaseOptions get options {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwr4HkXtJBszOwx9Afmv7IFDh2xhU0lB8',
    appId: '1:259273550318:web:68baf054f8bb8ab148c6ff',
    messagingSenderId: '259273550318',
    projectId: 'zitherharpnomna',
    authDomain: 'zitherharpnomna.firebaseapp.com',
    databaseURL:
        'https://zitherharpnomna-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zitherharpnomna.appspot.com',
    measurementId: 'G-RZXNP4D54W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVD0ozqyIDkLMy_Rq450MoYdp42G3J-U0',
    appId: '1:259273550318:android:4be4b55adc68582548c6ff',
    messagingSenderId: '259273550318',
    projectId: 'zitherharpnomna',
    databaseURL:
        'https://zitherharpnomna-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zitherharpnomna.appspot.com',
  );

  static const Map<String, String> parameters = {
    FlutterAppCheck.recaptchaSiteKey:
        '6LdQu3QpAAAAAKiTc3WMJnW03VSisgFiUmUsc9ob',
    FlutterAppCheck.recaptchaEnterpriseSiteKey:
        '6LcnvHQpAAAAAJJKf71RAgQ1DqWvOQBQt5LfoVzU',
  };
}
